ccflags-y := \
	-std=gnu11 \
	-Wno-declaration-after-statement \
	-D "strnlen_s(str, len)=((str != NULL) ? strnlen(str, len) : 0)" \
	-D _CLLTK_INTERNAL=1 \
	-finline-functions \
	-funroll-loops \
	-I$(src)

# gcc lowers _Atomic/__atomic to libgcc outline-atomics calls on aarch64
# (__aarch64_ldadd8_acq_rel, ...) which do not exist in kernel space; force
# inline atomic sequences instead. No-op on other architectures.
ccflags-y += $(call cc-option,-mno-outline-atomics)

# kernel module
obj-m := clltk_kernel_tracing.o

# abstraction
ccflags-y += -I$(src)/../../tracing_library/source/ -I$(src)/../../tracing_library/source/abstraction/include/
clltk_kernel_tracing-y +=  $(addprefix abstraction/, \
							error.o \
							file.o \
							info.o \
							memory.o \
							sync.o \
							)	

# shared code
ccflags-y += -I$(src)/../../tracing_library/include/
clltk_kernel_tracing-y +=  $(addprefix ../../tracing_library/source/, \
							arguments.o \
							tracebuffer.o \
							tracepoint.o \
							c-vector/vec.o \
							md5/md5.o \
							definition/definition.o \
							ringbuffer/ringbuffer.o \
							unique_stack/unique_stack.o \
							)

# kernel module entry code
clltk_kernel_tracing-y +=  module.o initialization.o
