#!/usr/bin/env bash
# Copyright (c) 2024, International Business Machines
# SPDX-License-Identifier: BSD-2-Clause-Patent

# Build a proper SRPM from the git source tree.
# Usage: build_srpm.sh <source_dir> <build_dir> <version>
#
# Produces: <build_dir>/packages/clltk-<version>-*.src.rpm
# Requires: git, rpmbuild

set -euo pipefail

SOURCE_DIR="$1"
BUILD_DIR="$2"
VERSION="$3"

RPMBUILD_DIR="${BUILD_DIR}/rpmbuild"
PACKAGES_DIR="${BUILD_DIR}/packages"
SPEC_FILE="${BUILD_DIR}/clltk.spec"

# Verify spec file was generated by CMake configure
if [ ! -f "${SPEC_FILE}" ]; then
    echo "ERROR: ${SPEC_FILE} not found. Run cmake configure first."
    exit 1
fi

# Create rpmbuild directory structure
mkdir -p "${RPMBUILD_DIR}/SOURCES" "${RPMBUILD_DIR}/SRPMS" "${PACKAGES_DIR}"

# Create source tarball from git
echo "Creating source tarball clltk-${VERSION}.tar.gz..."
git -C "${SOURCE_DIR}" archive \
    --format=tar.gz \
    --prefix="clltk-${VERSION}/" \
    -o "${RPMBUILD_DIR}/SOURCES/clltk-${VERSION}.tar.gz" \
    HEAD

# Build SRPM
echo "Building SRPM..."
rpmbuild -bs \
    --define "_topdir ${RPMBUILD_DIR}" \
    "${SPEC_FILE}"

# Copy SRPM to packages directory
SRPM=$(find "${RPMBUILD_DIR}/SRPMS" -name "clltk-${VERSION}-*.src.rpm" -print -quit)
if [ -z "${SRPM}" ]; then
    echo "ERROR: SRPM not found in ${RPMBUILD_DIR}/SRPMS/"
    exit 1
fi

cp -f "${SRPM}" "${PACKAGES_DIR}/"
echo "SRPM: ${PACKAGES_DIR}/$(basename "${SRPM}")"
