
option(ENABLE_CODE_COVERAGE "Enable code coverage" OFF)
if(ENABLE_CODE_COVERAGE)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        add_compile_options(-g -O0 --coverage -fprofile-update=atomic "-fprofile-exclude-files=.*(^/usr|tests|build|examples).*")
        add_link_options(--coverage -fprofile-update=atomic "-fprofile-exclude-files=.*(^/usr|tests|build|examples).*")
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        add_compile_options(-g -O0 --coverage -fprofile-update=atomic "-fprofile-exclude-files=.*(^/usr|tests|build|examples).*" -fprofile-reproducible=parallel-runs -fprofile-abs-path)
        add_link_options(--coverage -fprofile-update=atomic "-fprofile-exclude-files=.*(^/usr|tests|build|examples).*" -fprofile-reproducible=parallel-runs -fprofile-abs-path)
    else()
        message(FATAL_ERROR "Code coverage only works with Clang")
    endif()
endif()
