
option(ENABLE_CODE_COVERAGE "Enable code coverage" OFF)
if(ENABLE_CODE_COVERAGE)
    if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        add_compile_options(-g -O0 --coverage)
        add_link_options(--coverage)
    else()
        message(FATAL_ERROR "Code coverage only works with GCC or Clang")
    endif()
endif()
